### ISSUE TITLE
Not working for HTTP (plaintext) connections

### ISSUE THREAD

**Issue by lean0x2F** [xnuter/http-tunnel#6]
Hi! First of all, I apologize if this is a stupid question. I promise I read the docs.

I'm running http-tunnel using the following settings: 

CLI

```
$ ./target/release/http-tunnel --config ./config/config-browser.yaml --bind 0.0.0.0:8080 HTTP
```

Config

```yaml
client_connection:
  initiation_timeout: 100s
  relay_policy:
    idle_timeout: 300s
    min_rate_bpm: 0
    max_rate_bps: 10000000

target_connection:
  dns_cache_ttl: 60s
  allowed_targets: ".*" # anything
  connect_timeout: 100s
  relay_policy:
    idle_timeout: 100s
    min_rate_bpm: 0
    max_rate_bps: 10000000
```

I'm running into some issues when using it as an HTTP proxy. 

This works: `curl --proxy localhost:8080 https://api.ipify.org`
This doesn't work: `curl --proxy localhost:8080 http://api.ipify.org`

I have no idea what's happening. Any idea how to debug this issue?

Thank you very much for the tool ❤️ , it's working flawlessly for HTTPS and it's fast AF. It makes me want to learn to code in rust. 

Leandro
